<a href="https://colab.research.google.com/github/ShrishteeSingh/Shri/blob/master/churnModel3(Supervised%2BUnsupervised).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# reading the CSV file into pandas dataframe
from google.colab import files
uploaded = files.upload()
import io
dataset = pd.read_csv(io.BytesIO(uploaded['Churn_Modelling.csv'])) 
# This command helps us view the data 
dataset.head()

Saving Churn_Modelling.csv to Churn_Modelling (1).csv


RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

**Import the entire dataset to X except the 'Exited' label**

In [3]:
# Importing the dataset
# dataset = pd.read_csv('Churn_Modelling.csv')

X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

**Use One hot encoding to change categorical data(Geography & Gender) to numerical data**

In [4]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

**Add labels to the data using Columns feature**

In [6]:
X_label = pd.DataFrame(X, columns=('Credit Score','Geog','Gender','Age', 'Tenure', 'Balance', 'NumOfProd', 
                                   'Cr Card', 'Active', 'Est Salary'))
X_label

Credit Score Geog Gender Age  ... NumOfProd Cr Card Active Est Salary
0             619    0      0  42  ...         1       1      1     101349
1             608    2      0  41  ...         1       0      1     112543
2             502    0      0  42  ...         3       1      0     113932
3             699    0      0  39  ...         2       0      0    93826.6
4             850    2      0  43  ...         1       1      1    79084.1
...           ...  ...    ...  ..  ...       ...     ...    ...        ...
9995          771    0      1  39  ...         2       1      0    96270.6
9996          516    0      1  35  ...         1       1      1     101700
9997          709    0      0  36  ...         1       0      1    42085.6
9998          772    1      1  42  ...         2       1      0    92888.5
9999          792    0      0  28  ...         1       1      0    38190.8

[10000 rows x 10 columns]

**Normalize Data**

In [7]:
from sklearn.preprocessing import normalize
X_scaled = normalize(X_label)
X_data_norm = pd.DataFrame(X_scaled, columns=X_label.columns)
X_data_norm.head()
# Splitting the dataset into the Training set and Test set

Ch = X_data_norm
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Ch, y, test_size = 0.2, random_state = 0)
X_train.head()

Credit Score      Geog    Gender  ...   Cr Card    Active  Est Salary
7389      0.004071  0.000012  0.000000  ...  0.000006  0.000000    0.999992
9275      0.004504  0.000011  0.000011  ...  0.000011  0.000011    0.602265
2995      0.002466  0.000000  0.000000  ...  0.000005  0.000000    0.855473
5316      0.003218  0.000010  0.000005  ...  0.000005  0.000000    0.854186
356       0.004639  0.000011  0.000000  ...  0.000005  0.000005    0.722007

[5 rows x 10 columns]

In [8]:
ChCopy = Ch.copy()
Ch = X_train
Ch.reset_index(inplace=True)
Ch.drop(columns=['index'], inplace= True)
Ch.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Credit Score      Geog    Gender  ...   Cr Card    Active  Est Salary
0      0.004071  0.000012  0.000000  ...  0.000006  0.000000    0.999992
1      0.004504  0.000011  0.000011  ...  0.000011  0.000011    0.602265
2      0.002466  0.000000  0.000000  ...  0.000005  0.000000    0.855473
3      0.003218  0.000010  0.000005  ...  0.000005  0.000000    0.854186
4      0.004639  0.000011  0.000000  ...  0.000005  0.000005    0.722007

[5 rows x 10 columns]

**Applying Unsupervised Leaning:**

**Cluster Analysis**

In [0]:
import scipy.cluster.hierarchy as sch
from scipy.cluster.hierarchy import cophenet, dendrogram, linkage
from scipy.spatial.distance import pdist
%matplotlib inline

In [109]:
# Case 1: Ward Method
Z = linkage(Ch, 'ward')
c, coph_dists = cophenet(Z , pdist(Ch))
print("Ward",c)
# Case 2: Average Linkage
Z = linkage(Ch, 'average')
c, coph_dists = cophenet(Z , pdist(Ch))
print("Average", c)
# Case 3: Complete Linkage
Z = linkage(Ch, 'complete')
c, coph_dists = cophenet(Z , pdist(Ch))
print("Complete",c)

Ward 0.8246000730192902
Average 0.8477592020303483
Complete 0.7872016863349348


**Due to 10000 datapoints, using K Means clustering**

**Making two clusters**

In [0]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns
from sklearn.cluster import KMeans

In [89]:
#KMeans Clustring Algorithm
# Label, Interia and Centroid
cluster_range = range(2,3)
# expect 3 to 4 clusters from the pair panel visual inspection hence restricting from 2 to 6
cluster_errors = []
# sil stands for silhouette
cluster_sil_scores = []
for num_clusters in cluster_range:
  clusters = KMeans(num_clusters, init='k-means++')
  clusters.fit(Ch)
  labels = clusters.labels_        # capture the cluster labels
  centroids = clusters.cluster_centers_       # capture the centroid
  cluster_errors.append(clusters.inertia_)    # capture the inertia

# combine the cluster_range and cluster_errors into a dataframe by combining them
clusters_df = pd.DataFrame( {"num_clusters":cluster_range, "cluster_errors": cluster_errors})
clusters_df[0:15]

num_clusters  cluster_errors
0             2    1.669450e+10

**Adding another one extra feature Cluster**

In [13]:
num_clusters = 2
clusters = KMeans(num_clusters, init='k-means++')
clusters.fit(Ch)
labels = clusters.labels_    
Ch['cluster'] = labels
Ch  

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


Credit Score      Geog    Gender  ...    Active  Est Salary  cluster
0         0.004071  0.000012  0.000000  ...  0.000000    0.999992        0
1         0.004504  0.000011  0.000011  ...  0.000011    0.602265        1
2         0.002466  0.000000  0.000000  ...  0.000000    0.855473        1
3         0.003218  0.000010  0.000005  ...  0.000000    0.854186        1
4         0.004639  0.000011  0.000000  ...  0.000005    0.722007        1
...            ...       ...       ...  ...       ...         ...      ...
7995      0.002934  0.000005  0.000000  ...  0.000005    0.805057        1
7996      0.005051  0.000013  0.000000  ...  0.000006    0.685506        1
7997      0.003040  0.000000  0.000004  ...  0.000000    0.747400        1
7998      0.003966  0.000013  0.000000  ...  0.000007    0.999992        0
7999      0.003878  0.000006  0.000000  ...  0.000000    0.739854        1

[8000 rows x 11 columns]

**Taking cluster 1 and cluster 2 as c1 & c2 for further analysis.**

In [14]:
c1 = Ch[Ch.cluster == 1]
c2 = Ch[Ch.cluster == 0]
y1 = y_train[c1.index]
y2 = y_train[c2.index]
y1[0:10]


array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [131]:
Ch.shape,X_train.shape,y_train.shape
Ch.head(), y_train[0:10]
np.unique(y_train,return_counts=True)

(array([0, 1]), array([6368, 1632]))

In [136]:
#Ch1 = Ch.drop(columns=['cluster'])

Credit Score      Geog    Gender  ...    Active  Est Salary  cluster
0      0.004071  0.000012  0.000000  ...  0.000000    0.999992        0
1      0.004504  0.000011  0.000011  ...  0.000011    0.602265        1
2      0.002466  0.000000  0.000000  ...  0.000000    0.855473        1
3      0.003218  0.000010  0.000005  ...  0.000000    0.854186        1
4      0.004639  0.000011  0.000000  ...  0.000005    0.722007        1

[5 rows x 11 columns]

**Applying supervised learning on Cluster 1:
ANN**

In [37]:
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(c1, y1, batch_size = 50, epochs = 10)




Epoch 1/10





4755/4755 [==============================] - 0s 93us/step - loss: 0.6825 - acc: 0.7504
Epoch 2/10
4755/4755 [==============================] - 0s 27us/step - loss: 0.6620 - acc: 0.7567
Epoch 3/10
4755/4755 [==============================] - 0s 26us/step - loss: 0.6439 - acc: 0.7567
Epoch 4/10
4755/4755 [==============================] - 0s 27us/step - loss: 0.6283 - acc: 0.7567
Epoch 5/10
4755/4755 [==============================] - 0s 27us/step - loss: 0.6149 - acc: 0.7567
Epoch 6/10
4755/4755 [==============================] - 0s 27us/step - loss: 0.6038 - acc: 0.7567
Epoch 7/10
4755/4755 [==============================] - 0s 29us/step - loss: 0.5945 - acc: 0.7567
Epoch 8/10
4755/4755 [==============================] - 0s 29us/step - loss: 0.5868 - acc: 0.7567
Epoch 9/10
4755/4755 [==============================] - 0s 27us/step - loss: 0.5804 - acc: 0.7567
Epoch 10/10
4755/4755 [==============================] - 0s 27us/step - loss: 0.5751 - acc: 0.7567


In [38]:
X_test.drop(columns=['cluster'],inplace=True)
label = clusters.predict(X_test)
X_test['cluster'] = label
X_test.reset_index(inplace=True)
X_test.drop(columns=['index'],inplace=True)

c2_test = X_test[X_test.cluster == 0]
c1_test = X_test[X_test.cluster == 1]



/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/ind

 **Making the Confusion Matrix for Cluster 1 : ANN model**

In [44]:


from sklearn.metrics import confusion_matrix

y_pred1 = fit.predict(c1_test.values)
y_pred1 = (y_pred >= 0.5)
cm1 = confusion_matrix(y_test[c1_test.index], y_pred1)
cm1

/usr/local/lib/python3.6/dist-packages/statsmodels/discrete/discrete_model.py:1736: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))


array([[763, 170],
       [156, 133]])

**Accuracy for ANN model for Cluster 1 = 896/1222 = 73.3%**

**Applying supervised learning on Cluster 2 : ANN Model**

---



In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier2 = Sequential()

# Adding the input layer and the first hidden layer
classifier2.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier2.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier2.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier2.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier2.fit(c2, y2, batch_size = 10, epochs = 100)

In [48]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix

y_pred2 = fit.predict(c2_test.values)
y_pred2 = (y_pred2 >= 0.5)
cm2 = confusion_matrix(y_test[c2_test.index], y_pred2)
cm2

/usr/local/lib/python3.6/dist-packages/statsmodels/discrete/discrete_model.py:1736: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))


array([[462, 200],
       [ 51,  65]])

**ANN accuracy for cluster 2 = 527/778 = 67.73%**

**CART Model for Cluster 1**

In [52]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'gini', max_depth=3,random_state = 0)
classifier.fit(c1,y1)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test[c1_test.index], y_pred1)
cm

array([[763, 170],
       [156, 133]])

**Accuracy =73.3%**

**[CART model  for cluster 2]**

In [53]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'gini', max_depth=3,random_state = 0)
classifier.fit(c2,y2)

# Predicting the Test set results


# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test[c2_test.index], y_pred2)
cm

array([[462, 200],
       [ 51,  65]])

**Accuracy = 68.26%**

**Submitted by group 1:
Hrishita,
Sadhavi,
Shrishtee,
Soniya,
Vidhi**